version: "3.7"

services:
  db-integration:
    image: postgres:alpine
    ports:
      - published: 5433
        target: 5432
    environment:
      POSTGRES_DB: pipeliner
      POSTGRES_USER: pipeliner
      POSTGRES_PASSWORD: pipeliner
